config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:edit, :update]
  resources :songs do
    member { post :vote }
  end

  CodeJam::Application.routes.draw do
    get "/auth/:provider/callback" => "sessions#create"
    get "/signout" => "sessions#destroy", :as => :signout
    get "/login", to: "users#login"
    root to: "songs#index"
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
  validates :url, presence: true

  has_reputation :votes,
    :source => :user,
    :aggregated_by => :sum
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :songs

  has_reputation :votes, source: {reputation: :votes, of: :songs}, aggregated_by: :sum

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def authenticate
    if current_user.nil?
      return redirect_to root_url
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @songs = Song.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"])
    if user.nil?
      user = User.create_with_omniauth(auth)
      redirect_path = root_path
    else
      # redirect_path = user_path(user.id)
      redirect_path = root_path
    end
    session[:user_id] = user.id
    redirect_to redirect_path, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/songs_controller.rb
require "soundcloud"

class SongsController < ApplicationController
  # before_filter :authenticate

  def index
    @songs = Song.find_with_reputation(:votes, :all, order: "votes").sort_by(&:votes).reverse
    @songs = Kaminari.paginate_array(@songs).page(params[:page]).per(10)
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = current_user.songs.new
  end

  def create
    song = current_user.songs.new(song_params)
    if (params[:song][:url] =~ /soundcloud{1}/i)
      song.save
      redirect_to root_path
    else
      redirect_to new_song_path
    end
  end

  # def edit
  #   @song = current_user.url
  # end

  # def update
  #   @song = Song.find(params[:id])

    #   @song.update(song_params)
    #   redirect_to user_path[:id]
    #   params[:song].delete(:url)
    # end

    # if params[:song][:url].blank?
    #   flash[:error] = "Please enter a URL"
    # end

  # end

  def destroy
    @song = Song.find(params[:id])
    @song.delete_evaluation(:votes, current_user)
    @song.destroy
    redirect_to user_path(current_user.id)
  end

  def vote
    value = params[:type] == "like" ? 1 : -1
    @song = Song.find(params[:id])
    @song.add_or_update_evaluation(:votes, value, current_user)
    respond_to do |format|
      format.json do
        render :json => {
          :status => :ok,
          :message => "Success!",
          :votes => @song.reputation_for(:votes).to_i
        }.to_json
      end
    end
  end

  private
  def song_params
    params.require(:song).permit(:url, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, except: :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @songs = Song.find_with_reputation(:votes, :all, {:conditions => ['user_id = ?', @user.id], order: "votes"}).sort_by(&:votes).reverse
    @songs = Kaminari.paginate_array(@songs).page(params[:page]).per(10)

    # @songs = Song.where(user_id: @user.id).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    user.save
    redirect_to root_path
  end

  # def edit
  #   @user = current_user
  # end

  # def update
  #   @user = current_user

  #   if params[:user][:name].nil?
  #     params[:user].delete(:name)
  #   end

  #   @user.update(user_params)
  #   redirect_to user_path(params[:id])
  # end

  def destroy
    session[:user_id] = nil
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="large-6 medium-8 small-9 large-centered medium-centered small-centered columns top-space-80">
<!--   <h1>I Am the Player</h1>
  <p>home#index  root_path</p> -->

<% @songs.each do |song| %>
  <object height="50" width="100%">
    <param name="movie" value="https://player.soundcloud.com/player.swf?url=<%= song.url %>&player_type=tiny{widgetParams}"></param>
    <param name="allowscriptaccess" value="always"></param>
    <param name="wmode" value="transparent"></param>
    <embed wmode="transparent" allowscriptaccess="always" height="18" width="100%"     src="https://player.soundcloud.com/player.swf?    url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2Ferb<%= song.url %>">    </embed>
  </object>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "syntrax" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    <script src="//connect.soundcloud.com/sdk.js"></script>
    <!-- <script type="text/javascript" src="scripts/soundcloud.player.api.js"></script> -->
    <script>
      SC.initialize({
        client_id: "YOUR_CLIENT_ID"
        // redirect_uri: "http://example.com/callback.html",
      });
    </script>
  </head>

  <body>
    <div class="wrapper">
      <div class="contain-to-grid sticky">
        <nav class="top-bar" data-topbar data-options="sticky_on: large">
          <ul class="title-area">
            <li class="name"></li>
          </ul>
          <section class="top-bar-section no-color">
            <ul class="left">
              <a href="#" data-reveal-id="myModal" title="About">About</a>
              <div id="myModal" class="reveal-modal" data-reveal>
                <h2>Jam on it.</h2>
                <p>Music is a huge driving force in most people's lives and can be very inspirational.  The idea behind syntrax is for other developers to be able to share what they are listening to and coding to.  You need good syntrax for good syntax.</p>
                <p>I'm always posting what I'm listening to on my Twitter.  Follow or just check me out to see what I'm listening to.<br><a href="http://twitter.com/yungwelchsgrape" target="_blank" class="white-text">@yungwelchsgrape</a></p>
                <a class="close-reveal-modal">&#215;</a>
              </div>
            </ul>
            <ul class="right">
              <% if current_user %>
                <li class="username"><span>Hey, <%= current_user.name %>! </span></li>
                <li><span title="Home"><%= link_to "Home", root_path %></span></li>
                <li><span title="Add a Song"><%= link_to "Add a Song", new_song_path %></span></li>
                <li><span title="My Songs"><%= link_to "My Songs", user_path(current_user.id) %></span></li>
                <li><span title="Sign out"><%= link_to "Sign out", signout_path %></span></li>
              <% else %>
                <li><span title="Sign in"><%= link_to "Sign in with GitHub", "/auth/github" %></span></li>
              <% end %>
              <li class="toggle-topbar menu-icon"><a href="#"><span>MENU</span></a></li>
            </ul>
          </section>
        </nav>
      </div>
    </div>


    <div class="row">
      <div class="large-9 medium-8 small-9 large-centered medium-centered small-centered columns top-space-80" id="form">
        <div id="logo"><%= link_to image_tag("logo2.png", :border => 0), root_url %></div>
      </div>
    </div>

    <div class="row">
    <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
    <%= yield :js %>
  </body>
</html>

app/views/songs/index.html.erb
<div class="large-8 medium-8 small-9 large-centered medium-centered small-centered columns top-space-80" id="box">
  <% @songs.each_with_index do |s, i| %>
    <div data-track-id="<%= i %>" class="track">
      <object height="20px" width="100%" id="song<%= i %>" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
        <param name="movie" value="http://player.soundcloud.com/player.swf?url=<%= s.url %>&enable_api=true&player_type=tiny&show_comments=false&object_id=song<%= i %>"></param>
        <param name="allowscriptaccess" value="always"></param>
        <param name="wmode" value="transparent"></param>
        <embed wmode="transparent" allowscriptaccess="always" height="18" width="100%" src="http://player.soundcloud.com/player.swf?url=<%= s.url %>&player_type=tiny&enable_api=true&object_id=song<%= i %>" name="song<%= i %>"></embed>
      </object>
      <p id="share">Shared by: <a href="/users/<%= s.user.id %>" class="shared-by"><%= s.user.name %></a></p>
      <div>
        <div class="total">
          <%= pluralize s.reputation_for(:votes).to_i, "reps" %>
        </div>
        <div class="likes">
          <% if current_user%>
            <%= link_to "hot", vote_song_path(s), class: "like vote", data: { type: "like" } %> <span style="color: white">|</span>
            <%= link_to "wack", vote_song_path(s), class: "dislike vote", data: { type: "dislike" } %>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
<%= paginate @songs %>
</div>

<% content_for :js do %>
  <script type="text/javascript">
    soundcloud.addEventListener('onMediaEnd', function(player, data) {
      console.log("end!");
      var nextNumber = parseInt(player.name.substr(-1)) + 1;
      console.log(nextNumber);
      var nextSong = "song" + nextNumber;
      soundcloud.getPlayer(nextSong).api_play();
    });
    soundcloud.addEventListener('onPlayerReady', function(player, data) {
      console.log('readddyyy');
    });
    soundcloud.addEventListener('onMediaSeek', function(player, data) {
      console.log('seek!')
    });
  </script>
<% end %>

app/views/songs/new.html.erb
<div class="row">
  <div class="large-6 medium-8 small-9 large-centered medium-centered small-centered columns top-space-80" id="box2">
    <h4>Add a Song</h4>
    <%= form_tag(songs_path , method: "post") do %>
    <%= label_tag "song[url]", "SoundCloud URL", :class => "sc-url" %>
    <%= text_field_tag("song[url]") %>
    <%= submit_tag("SUBMIT") %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="large-8 medium-8 small-9 large-centered medium-centered small-centered columns top-space-80" id="box">
  <h4><%= @user.name %> has <%= @user.reputation_for(:votes).to_i %> reps</h4>
  <% @songs.each_with_index do |s, i| %>
    <div data-track-id="<%= i %>" class="track">
      <object height="20px" width="100%" id="song<%= i %>" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
        <param name="movie" value="http://player.soundcloud.com/player.swf?url=<%= s.url %>&enable_api=true&player_type=tiny&show_comments=false&object_id=song<%= i %>"></param>
        <param name="allowscriptaccess" value="always"></param>
        <param name="wmode" value="transparent"></param>
        <embed wmode="transparent" allowscriptaccess="always" height="18" width="100%" src="http://player.soundcloud.com/player.swf?url=<%= s.url %>&player_type=tiny&enable_api=true&object_id=song<%= i %>" name="song<%= i %>"></embed>
      </object>
    </div>
    <div class="total">
      <%= pluralize s.reputation_for(:votes).to_i, "reps" %>
    </div>
    <% if current_user == @user %>
      <%= link_to(" Delete?", song_path(s.id), method: "delete", confirm: 'Are you sure?') %>
    <% end %>
    <hr>
  <% end %>
<%= paginate @songs %>
</div>



<% content_for :js do %>
  <script type="text/javascript">
    soundcloud.addEventListener('onMediaEnd', function(player, data) {
      console.log("end!");

      var nextNumber = parseInt(player.name.substr(-1)) + 1;
      console.log(nextNumber);
      var nextSong = "song" + nextNumber;
      soundcloud.getPlayer(nextSong).api_play();
    });
    soundcloud.addEventListener('onPlayerReady', function(player, data) {
      console.log('readddyyy');
    });
    soundcloud.addEventListener('onMediaSeek', function(player, data) {
      console.log('seek!')
    });
  </script>
<% end %>